version: '2'

networks:
  custom:
    driver: bridge

services:
  control:
    image: control
    ports:
      - "8000:8000"
      - "2222:22"
    environment:
      CODEBOX_USERNAME: devops
      CODEBOX_PASSWORD: codespaces
    volumes:
      - ./code:/workspace
    networks:
      - custom
    container_name: control
    domainname: schoolofdevops.com
    hostname: control
    restart: always
  node1:
    image: schoolofdevops/cs-ansible-centos:latest
    container_name: lb
    ports:
       - "2223:22"
       - "8080:80"
    networks:
      - custom
    domainname: schoolofdevops.com
    hostname: lb
    restart: always
  node2:
    image: node
    ports:
       - "2224:22"
       - "81:80"
    networks:
      - custom
    container_name: app1
    domainname: schoolofdevops.com
    hostname: app1
    restart: always
  node3:
    image: schoolofdevops/ubuntu-node:v1.1
    ports:
      - "2225:22"
      - "82:80"
    networks:
      - custom
    container_name: app2
    domainname: schoolofdevops.com
    hostname: app2
    restart: always
  node4:
    image: schoolofdevops/cs-ansible-centos:latest
    ports:
      - "2226:22"
      - "3306:3306"
    networks:
      - custom
    container_name: db
    domainname: schoolofdevops.com
    hostname: db
    restart: always
